config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'business_files#index'
  resources :business_files, only: [:new, :create, :index] do
    resources :documents, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_file.rb
class BusinessFile < ApplicationRecord
  belongs_to :user

  validates :file_title, presence: true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :business_file

  validates :company_name, presence: true
  validates :company_name_kana, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :business_files

  validates :name,                  presence: true
  validates :password,              format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/ }
  validates :password_confirmation, format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/business_files_controller.rb
class BusinessFilesController < ApplicationController
  def index
  end

  def new
    @file = BusinessFile.new
  end

  def create
    @file = BusinessFile.new(file_params)

    if @file.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def file_params
    params.require(:business_file).permit(:file_title, user_ids: [])
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  # def index
  # @documents = Document.order("name")
  # @file = BusinessFile.find(params[:business_file_id])
  # end

  def new
    @document = Document.new
  end

  def create
    @document = Documents.new(document_params)
    if @document.save
      redirect_to business_file_documents_path
    else
      render :new
    end
  end

  private

  def document_params
    params.require(:document).permit(:company_name, :company_name_kana, :title).merge(item_id: @item.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_files_helper.rb
module BusinessFilesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/business_files/index.html.erb
  <header class="top-page-header">
  <nav class="navbar navbar-light" style="background-color: #fff8ed;">
    <div class="container-fluid">
      <a class="navbar-brand">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journals" viewBox="0 0 16 16">
          <path d="M5 0h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2 2 2 0 0 1-2 2H3a2 2 0 0 1-2-2h1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1H1a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v9a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1H3a2 2 0 0 1 2-2z"/>
          <path d="M1 6v-.5a.5.5 0 0 1 1 0V6h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V9h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 2.5v.5H.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1H2v-.5a.5.5 0 0 0-1 0z"/>
        </svg>Filing Application
      </a>

      <form class="d-flex">
        <%= link_to(new_business_file_path, class:"create-btn btn btn-outline-success") do %>Create 
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-check" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
          </svg>
        <% end %>
      
        <%= link_to(destroy_user_session_path, method: :delete, class:"log-out-btn btn btn-outline-danger") do %>Log out 
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        <% end %>
      </form>
    </div>
  </nav>
</header>

<body class="top-page-body">

  <h1 class="text-center text-white text-opacity-75 m-5"><%= "#{current_user.name}'s File shelves" %></h1>

    <div class="container-fluid">
      <div class="row flex-nowrap">
        <% current_user.business_files.each do |file| %>
          <div class="file-info col">
            <div class="card">
              <ul>
                <li>
                  <%= link_to(root_path, class:"file-link") do %>
                    <div class="card-body file-outer-frame">
                      <h2 class='file-titles'><%= file.file_title %></h2>
                    </div>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>

</body>

app/views/business_files/new.html.erb
  <header class="top-page-header">
    <nav class="navbar navbar-light" style="background-color: #fff8ed;">
      <div class="container-fluid">

        <a class="navbar-brand">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journals" viewBox="0 0 16 16">
            <path d="M5 0h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2 2 2 0 0 1-2 2H3a2 2 0 0 1-2-2h1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1H1a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v9a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1H3a2 2 0 0 1 2-2z"/>
            <path d="M1 6v-.5a.5.5 0 0 1 1 0V6h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V9h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 2.5v.5H.5a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1H2v-.5a.5.5 0 0 0-1 0z"/>
          </svg>Filing Application
        </a>
        <form class="d-flex">
          <%= link_to(root_path, class:"create-btn btn btn-outline-success") do %>Return 
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
          </svg>
        <% end %>
        <%= link_to(destroy_user_session_path, method: :delete, class:"log-out-btn btn btn-outline-danger") do %>Log out 
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
          </svg>
        <% end %>

      </div>
    </form>
  </nav>
</header>

<body class="file-create-page-body">
  <section class="bg-dark p-2 text-dark bg-opacity-50 p-5 mt-10">
    <h1 class="text-center text-white text-opacity-75 m-5">PLEASE MAKE A FILE!!</h1>
  
    <%= form_with model: @file, local: true do |f| %>
      <h3 class="text-white">File Name</h3>

	    <div class="container">
			  <div class="row">
	  		  <div class="col">
	 				  <%= f.text_area :file_title, class:"file-title form-control mb-2", id:"file-title", placeholder:" " %>
  			  </div>
  			  <div class="col">
  				  <%= f.submit "Create", class:"btn btn-danger rounded-pill mb-2" %>
				  </div>
			  </div>
		  </div>

	    <div class="error-color">
		    <%= render 'shared/error_messages', model: f.object %>
	    </div>
    <% end %>

  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>